{{- if .Values.mariadb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: db-auth-secret
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
data:
  DB_PORT: {{ .Values.mariadb.primary.service.port.mysql | b64enc | quote }}
  {{- with .Values.mariadb.auth }}
  DB_USER: {{ .username | b64enc | quote }}
  DB_PASS: {{ .password | b64enc | quote }}
  DB_NAME: {{ .database | b64enc | quote }}
  {{- end }}
{{- end }}
