{{- if .Values.queryservice.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryservice
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryservice
      {{- include "wikibase.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: queryservice
        {{- include "wikibase.labels" . | nindent 8 }}
    spec:
    {{- if .Values.queryservice.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.queryservice.affinity "context" $) | nindent 8 }}
    {{- else }}
      affinity:
      {{- if .Values.queryservice.podAffinity }}
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.queryservice.podAffinityPreset "component" "queryservice" "context" $) | nindent 10 }}
      {{- end }}
      {{- if .Values.queryservice.podAntiAffinity }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.queryservice.podAntiAffinityPreset "component" "queryservice" "context" $) | nindent 10 }}
      {{- end }}
      {{- if .Values.queryservice.nodeAffinity }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.queryservice.nodeAffinityPreset.type "key" .Values.queryservice.nodeAffinityPreset.key "values" .Values.queryservice.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
    {{- end }}
    {{- if .Values.queryservice.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.queryservice.nodeSelector "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.queryservice.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.queryservice.tolerations "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.queryservice.schedulerName }}
      schedulerName: {{ .Values.queryservice.schedulerName }}
    {{- end }}
    {{- if .Values.queryservice.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.queryservice.topologySpreadConstraints "context" $) | nindent 8 }}
    {{- end }}
    {{- if .Values.queryservice.priorityClassName }}
      priorityClassName: {{ .Values.queryservice.priorityClassName | quote }}
    {{- else if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
    {{- end }}
      containers:
        - name: queryservice
          args:
            - /runBlazegraph.sh
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WDQS_HOST
              value: "queryservice.$(NAMESPACE).svc.cluster.local"
            - name: WDQS_PORT
              value: {{ .Values.queryservice.service.port | default 9999 | quote }}
          {{- if .Values.wikibase.enabled }}
            - name: WIKIBASE_HOST
              value: "wikibase.$(NAMESPACE).svc.cluster.local"
          {{- end }}
          image: "{{ .Values.queryservice.image.repository }}:{{ .Values.queryservice.image.tag }}"
          ports:
            - name: wdqs
              containerPort: 9999
        {{- if .Values.queryservice.persistence.enabled }}
          volumeMounts:
            - name: queryservice-data
              mountPath: /wdqs/data
        {{- end }}
      restartPolicy: Always
      volumes:
      {{- if .Values.queryservice.persistence.enabled }}
        - name: queryservice-data
          persistentVolumeClaim:
            claimName: queryservice-data
      {{- end }}
{{- end -}}
