{{- if .Values.queryservice.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: queryservice
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: queryservice-ui
      {{- include "wikibase.labels" . | nindent 6 }}
  ports:
    - name: wdqs
      port: {{ .Values.queryservice.port }}
      targetPort: wdqs
status:
  loadBalancer: {}
