{{- if and .Values.queryservice.enabled .Values.queryservice.ui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryservice-ui
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queryservice-ui
      {{- include "wikibase.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: queryservice-ui
        {{- include "wikibase.labels" . | nindent 8 }}
    spec:
      containers:
        - name: queryservice-ui
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: WDQS_HOST
              value: "queryservice.$(NAMESPACE).svc.cluster.local"
          {{- if .Values.wikibase.enabled }}
            - name: WIKIBASE_HOST
              value: "wikibase.$(NAMESPACE).svc.cluster.local"
          {{- end }}
          image: "{{ .Values.queryservice.ui.image.repository }}:{{ .Values.queryservice.ui.image.tag }}"
          ports:
            - name: http
              containerPort: 80
      restartPolicy: Always
{{- end -}}
