apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f ./docker-compose.resolved.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: wdqs-proxy
  name: wdqs-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: wdqs-proxy
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f ./docker-compose.resolved.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: wdqs-proxy
    spec:
      containers:
        - env:
            - name: PROXY_PASS_HOST
              value: wdqs.svc:9999
          image: wikibase/wdqs-proxy:wmde.5
          name: wdqs-proxy
          resources: {}
      restartPolicy: Always
status: {}
