{{- if .Values.quickstatements.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: quickstatements
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: quickstatements
      {{- include "wikibase.labels" . | nindent 6 }}
  ports:
    - name: quickstatements
      port: {{ .Values.quickstatements.service.port }}
      targetPort: http
{{- end -}}
