{{- if .Values.global.shared.enabled -}}
{{- with .Values.global.shared }}
{{- if .persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
  annotations:
  {{- if .persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .persistence.storageClass | quote }}
  {{- else }}
    volume.beta.kubernetes.io/storage-class: "default"
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .volume.size | quote }}
    {{- if .persistence.storageClass }}
    {{- if (eq "-" .persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: {{ .persistence.storageClass | quote }}
    {{- end }}
    {{- end }}
{{- end }}
{{- end }}
{{- end -}}
