{{- if .Values.wikibase.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: wikibase-auth-secret
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
data:
  {{- with .Values.wikibase.auth }}
  MW_ADMIN_NAME: {{ .admin.username | b64enc | quote }}
  MW_ADMIN_PASS: {{ .admin.password | b64enc | quote }}
  MW_ADMIN_EMAIL: {{ .admin.email | b64enc | quote }}
  MW_WG_SECRET_KEY: {{ .secret | b64enc | quote }}
  {{- end }}
{{- end }}
