{{- if .Values.wikibase.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikibase
  labels:
    {{- include "wikibase.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wikibase
      {{- include "wikibase.labels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wikibase
        {{- include "wikibase.labels" . | nindent 8 }}
    spec:
      containers:
        - name: wikibase
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MW_ADMIN_NAME
              valueFrom:
                secretKeyRef:
                  name: wikibase-auth-secret
                  key: MW_ADMIN_NAME
            - name: MW_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: wikibase-auth-secret
                  key: MW_ADMIN_PASS
            - name: MW_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: wikibase-auth-secret
                  key: MW_ADMIN_EMAIL
            - name: MW_WG_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wikibase-auth-secret
                  key: MW_WG_SECRET_KEY
          {{- if .Values.mariadb.enabled }}
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: DB_PASS
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-auth-secret
                  key: DB_PORT
            - name: DB_SERVER
              value: "$(NAMESPACE)-mariadb.$(NAMESPACE).svc.cluster.local:$(DB_PORT)"
          {{- else }}
            {{- with .Values.wikibase.auth.externalDatabase }}
            - name: DB_NAME
              value: {{ .database | quote }}
            - name: DB_USER
              value: {{ .user | quote }}
            - name: DB_PASS
              value: {{ .password | quote }}
            - name: DB_SERVER
              value: "{{ .host }}:{{ .port }}"
            {{- end }}
          {{- end }}
            - name: MW_WG_JOB_RUN_RATE
            {{- if .Values.wikibase.jobrunner.enabled }}
              value: "0"
            {{- else }}
              value: "1"
            {{- end }}
            - name: WIKIBASE_HOST
              value: "wikibase.$(NAMESPACE).svc.cluster.local"
          {{- if .Values.elasticsearch.enabled }}
            - name: MW_ELASTIC_HOST
              value: "elasticsearch.$(NAMESPACE).svc.cluster.local"
            - name: MW_ELASTIC_PORT
              value: "9200"
          {{- end }}
          {{- if .Values.queryservice.enabled }}
            - name: WDQS_PORT
              value: {{ (.Values.queryservice.service.port | default 9999) | quote }}
          {{- end }}
          {{- if .Values.quickstatements.enabled }}
            - name: QS_PUBLIC_SCHEME_HOST_AND_PORT
              value: "http://quickstatements.$(NAMESPACE).srv.cluster.local:$(WDQS_PORT)"
          {{- end }}
          image: "{{ .Values.wikibase.image.repository }}:{{ .Values.wikibase.image.tag }}"
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
          {{- if and .Values.global.shared.enabled .Values.global.shared.persistence.enabled }}
            - name: shared-data
              mountPath: /var/www/html
          {{- end }}
          {{- if and .Values.quickstatements.enabled .Values.quickstatements.persistence.enabled }}
            - name: quickstatements-data
              mountPath: /quickstatements/data
          {{- end }}
          {{- if .Values.wikibase.persistence.enabled }}
            - name: wikibase-data
              mountPath: /extra-install.sh
          {{- end }}
      restartPolicy: Always
      volumes:
      {{- if and .Values.global.shared.enabled .Values.global.shared.persistence.enabled }}
        - name: shared-data
          persistentVolumeClaim:
            claimName: shared-data
      {{- end }}
      {{- if and .Values.quickstatements.enabled .Values.quickstatements.persistence.enabled }}
        - name: quickstatements-data
          persistentVolumeClaim:
            claimName: quickstatements-data
      {{- end }}
      {{- if .Values.wikibase.persistence.enabled }}
        - name: wikibase-data
          persistentVolumeClaim:
            claimName: wikibase-data
      {{- end }}
{{- end -}}
