global:
  shared:
    enabled: true
    persistence:
      enabled: true
      volume:
        size: 20Gi

mariadb:
  enabled: true
  global:
    storageClass: "default"
  image:
    repository: bitnami/mariadb
    tag: 10.6.9
    pullPolicy: IfNotPresent
  auth:
    rootPassword: ""
    username: "wikibase"
    password: "password"
    database: "wikibase"
  data:
    persistence:
      enabled: true
      size: 20Gi

elasticsearch:
  enabled: true
  image:
    repository: wikibase/elasticsearch
    tag: 6.8.23-wmde.5
  volume:
    size: 10Gi

queryservice:
  enabled: true
  volume:
    size: 40Gi

quickstatements:
  enabled: true
  port: 8840
  image:
    repository: wikibase/quickstatements
    tag: wmde.5
  env:
    - name: WB_ITEM_NAMESPACE
      value: "120"
    - name: WB_ITEM_PREFIX
      value: 'Item:'
    - name: WB_PROPERTY_NAMESPACE
      value: "122"
    - name: WB_PROPERTY_PREFIX
      value: 'Property:'
  volume:
    size: 40Gi
